#!/usr/bin/env bash
# load-secrets.sh — fetch secrets from Azure Key Vault using the VM's
# user-assigned managed identity and write the Docker .env file.
# Run once at boot by culvertsense-secrets.service before docker compose up.

set -euo pipefail

KV_URI="https://culvertsense-vm-kv.vault.azure.net"
API_VERSION="7.4"
DOCKER_DIR="/opt/culvertsense/docker"
ENV_FILE="${DOCKER_DIR}/.env"
CHIRPSTACK_TOML="${DOCKER_DIR}/config/chirpstack/chirpstack.toml"
CHIRPSTACK_TOML_TPL="${DOCKER_DIR}/config/chirpstack/chirpstack.toml.tpl"

# ---------------------------------------------------------------------------
# 1. Obtain an access token via IMDS using the user-assigned managed identity
# ---------------------------------------------------------------------------
TOKEN=$(curl -sf \
  "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net" \
  -H "Metadata: true" | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")

# ---------------------------------------------------------------------------
# 2. Helper: fetch a single secret value
# ---------------------------------------------------------------------------
kv_get() {
  local name="$1"
  curl -sf \
    "${KV_URI}/secrets/${name}?api-version=${API_VERSION}" \
    -H "Authorization: Bearer ${TOKEN}" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['value'])"
}

# ---------------------------------------------------------------------------
# 3. Fetch secrets
# ---------------------------------------------------------------------------
POSTGRES_PASSWORD=$(kv_get "postgres-password")
CHIRPSTACK_API_SECRET=$(kv_get "chirpstack-api-secret")
INFLUXDB_ADMIN_PASSWORD=$(kv_get "influxdb-admin-password")
INFLUXDB_ADMIN_TOKEN=$(kv_get "influxdb-admin-token")

# ---------------------------------------------------------------------------
# 4. Write .env (overwrite on every boot so rotations are picked up)
# ---------------------------------------------------------------------------
cat > "${ENV_FILE}" <<EOF
# Auto-generated by load-secrets.sh — do not edit manually
POSTGRES_USER=chirpstack
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=chirpstack

CHIRPSTACK_API_SECRET=${CHIRPSTACK_API_SECRET}

INFLUXDB_ADMIN_USER=admin
INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
INFLUXDB_ORG=culvertsense
INFLUXDB_BUCKET=sensors
INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
EOF

chmod 600 "${ENV_FILE}"

# ---------------------------------------------------------------------------
# 5. Render chirpstack.toml from template (replace placeholders)
# ---------------------------------------------------------------------------
sed \
  -e "s|__POSTGRES_PASSWORD__|${POSTGRES_PASSWORD}|g" \
  -e "s|__CHIRPSTACK_SECRET__|${CHIRPSTACK_API_SECRET}|g" \
  "${CHIRPSTACK_TOML_TPL}" > "${CHIRPSTACK_TOML}"

chmod 644 "${CHIRPSTACK_TOML}"

echo "load-secrets: secrets written successfully"
